#!/usr/bin/env bash
# Set domain HTTPS (Cloudflare) pada instalasi CreativePOS yang sudah jalan.
# Usage: sudo bash scripts/configure-domain.sh pos.domain-anda.com

set -euo pipefail

DOMAIN="${1:-}"
if [[ -z "$DOMAIN" ]]; then
  echo "Usage: sudo bash scripts/configure-domain.sh pos.domain-anda.com"
  exit 1
fi

DOMAIN="${DOMAIN#https://}"
DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%%/*}"
DOMAIN="${DOMAIN%%:*}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_ENV="$ROOT/backend/.env"
DOCKER_DIR="$ROOT/docker"

if [[ ! -f "$BACKEND_ENV" ]]; then
  echo "backend/.env tidak ditemukan. Jalankan install.sh dulu."
  exit 1
fi

APP_URL="https://${DOMAIN}"

echo "=== Konfigurasi domain: $APP_URL ==="

sed -i "s|^APP_URL=.*|APP_URL=${APP_URL}|" "$BACKEND_ENV"
sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=${APP_URL}|" "$BACKEND_ENV"
sed -i "s/^SANCTUM_STATEFUL_DOMAINS=.*/SANCTUM_STATEFUL_DOMAINS=${DOMAIN},localhost,127.0.0.1/" "$BACKEND_ENV"
sed -i "s/^REVERB_HOST=.*/REVERB_HOST=${DOMAIN}/" "$BACKEND_ENV"
sed -i "s/^REVERB_SCHEME=.*/REVERB_SCHEME=https/" "$BACKEND_ENV"
sed -i "s/^REVERB_PORT=.*/REVERB_PORT=443/" "$BACKEND_ENV"

if grep -q '^TRUSTED_PROXIES=' "$BACKEND_ENV"; then
  sed -i 's/^TRUSTED_PROXIES=.*/TRUSTED_PROXIES=*/' "$BACKEND_ENV"
else
  echo 'TRUSTED_PROXIES=*' >> "$BACKEND_ENV"
fi

if [[ -f "$ROOT/docker/.env" ]]; then
  sed -i "s/^APP_HOST=.*/APP_HOST=${DOMAIN}/" "$ROOT/docker/.env"
fi

cat > "$ROOT/frontend/.env.local" <<EOF
# Auto-generated by configure-domain.sh
NEXT_PUBLIC_API_URL=/api/v1
EOF

cd "$DOCKER_DIR"
docker compose -f docker-compose.client.yml exec -T backend php artisan config:clear
docker compose -f docker-compose.client.yml exec -T backend php artisan config:cache
docker compose -f docker-compose.client.yml exec -T backend php artisan route:cache
docker compose -f docker-compose.client.yml restart nginx backend frontend reverb

echo ""
echo "Selesai."
echo "Web   : $APP_URL"
echo "Mobile: masukkan $APP_URL di Setup Server aplikasi"