#!/usr/bin/env bash
# CreativePOS — Instalasi server client (Linux / Ubuntu)
# Usage: bash scripts/install-client.sh [APP_HOST] [APP_PORT]

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_HOST="${1:-}"
APP_PORT="${2:-80}"
SKIP_SEED="${SKIP_SEED:-0}"

detect_ip() {
  hostname -I 2>/dev/null | awk '{print $1}'
}

if [[ -z "$APP_HOST" ]]; then
  APP_HOST="$(detect_ip)"
  if [[ -z "$APP_HOST" ]]; then
    read -rp "Masukkan IP/hostname server: " APP_HOST
  else
    echo "Menggunakan IP LAN: $APP_HOST"
  fi
fi

if [[ "$APP_PORT" == "80" ]]; then
  APP_URL="http://${APP_HOST}"
else
  APP_URL="http://${APP_HOST}:${APP_PORT}"
fi

echo ""
echo "=== CreativePOS Client Install ==="
echo "URL akses: $APP_URL"
echo ""

command -v docker >/dev/null || { echo "Docker belum terinstall."; exit 1; }

# docker/.env
if [[ ! -f "$ROOT/docker/.env" ]]; then
  cp "$ROOT/docker/.env.example" "$ROOT/docker/.env"
fi
sed -i "s/^APP_HOST=.*/APP_HOST=${APP_HOST}/" "$ROOT/docker/.env"
sed -i "s/^APP_PORT=.*/APP_PORT=${APP_PORT}/" "$ROOT/docker/.env"

# backend/.env
if [[ ! -f "$ROOT/backend/.env" ]]; then
  cp "$ROOT/backend/.env.example" "$ROOT/backend/.env"
fi

REVERB_KEY="$(openssl rand -base64 24 | tr -d '/+=' | head -c 20)"
REVERB_SECRET="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"

sed -i 's/^APP_ENV=.*/APP_ENV=production/' "$ROOT/backend/.env"
sed -i 's/^APP_DEBUG=.*/APP_DEBUG=false/' "$ROOT/backend/.env"
sed -i "s|^APP_URL=.*|APP_URL=${APP_URL}|" "$ROOT/backend/.env"
sed -i 's/^DB_HOST=.*/DB_HOST=mysql/' "$ROOT/backend/.env"
sed -i 's/^REDIS_HOST=.*/REDIS_HOST=redis/' "$ROOT/backend/.env"

# Sinkronkan kredensial DB dari docker/.env
DB_NAME="$(grep -E '^DB_DATABASE=' "$ROOT/docker/.env" | cut -d= -f2- | tr -d '\r')"
DB_USER="$(grep -E '^DB_USERNAME=' "$ROOT/docker/.env" | cut -d= -f2- | tr -d '\r')"
DB_PASS="$(grep -E '^DB_PASSWORD=' "$ROOT/docker/.env" | cut -d= -f2- | tr -d '\r')"
[[ -n "$DB_NAME" ]] && sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${DB_NAME}/" "$ROOT/backend/.env"
[[ -n "$DB_USER" ]] && sed -i "s/^DB_USERNAME=.*/DB_USERNAME=${DB_USER}/" "$ROOT/backend/.env"
[[ -n "$DB_PASS" ]] && sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=${DB_PASS}/" "$ROOT/backend/.env"
sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=${APP_URL}|" "$ROOT/backend/.env"
sed -i "s/^SANCTUM_STATEFUL_DOMAINS=.*/SANCTUM_STATEFUL_DOMAINS=${APP_HOST},localhost,127.0.0.1/" "$ROOT/backend/.env"
sed -i "s/^REVERB_HOST=.*/REVERB_HOST=${APP_HOST}/" "$ROOT/backend/.env"
sed -i 's/^REVERB_PORT=.*/REVERB_PORT=80/' "$ROOT/backend/.env"
sed -i 's/^REVERB_SCHEME=.*/REVERB_SCHEME=http/' "$ROOT/backend/.env"
sed -i "s/^REVERB_APP_KEY=.*/REVERB_APP_KEY=${REVERB_KEY}/" "$ROOT/backend/.env"
sed -i "s/^REVERB_APP_SECRET=.*/REVERB_APP_SECRET=${REVERB_SECRET}/" "$ROOT/backend/.env"

cat > "$ROOT/frontend/.env.local" <<EOF
# Auto-generated by install-client.sh
NEXT_PUBLIC_API_URL=/api/v1
EOF

cd "$ROOT/docker"

echo "Membangun dan menjalankan container..."
docker compose -f docker-compose.client.yml up -d --build

echo "Menunggu MySQL siap..."
for i in $(seq 1 45); do
  if docker compose -f docker-compose.client.yml exec -T mysql mysqladmin ping -h localhost --silent 2>/dev/null; then
    echo "MySQL siap."
    break
  fi
  sleep 2
done

docker compose -f docker-compose.client.yml exec -T backend php artisan key:generate --force
docker compose -f docker-compose.client.yml exec -T backend php artisan storage:link --force || true

if [[ "$SKIP_SEED" == "1" ]]; then
  docker compose -f docker-compose.client.yml exec -T backend php artisan migrate --force
else
  docker compose -f docker-compose.client.yml exec -T backend php artisan migrate --seed --force
fi

docker compose -f docker-compose.client.yml exec -T backend php artisan config:cache
docker compose -f docker-compose.client.yml exec -T backend php artisan route:cache

echo ""
echo "=== Instalasi selesai ==="
echo "Web    : $APP_URL"
echo "POS    : $APP_URL/pos"
echo "Daftar : $APP_URL/register"
echo ""
echo "Android: pasang APK lalu arahkan ke $APP_URL"