# CreativePOS — Instalasi server client (Windows + Docker Desktop)
# Usage: powershell -ExecutionPolicy Bypass -File scripts\install-client.ps1

param(
    [string]$AppHost = "",
    [int]$AppPort = 80,
    [switch]$SkipSeed
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = Split-Path -Parent $ScriptDir

. (Join-Path $ScriptDir "lib\Resolve-AppHost.ps1")
$resolved = Resolve-AppHost -Root $Root -CliHost $AppHost -CliPort $AppPort

$AppHost = $resolved.AppHost
$AppPort = $resolved.Port
$AppScheme = $resolved.Scheme
$AppUrl = $resolved.Url

Write-Host "Host   : $AppHost (sumber: $($resolved.Source))"
if ($AppScheme -eq 'https') {
    Write-Host "HTTPS  : ya"
}

Write-Host "`n=== CreativePOS Client Install ===" -ForegroundColor Cyan
Write-Host "URL akses: $AppUrl"
Write-Host "Root: $Root`n"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "Docker tidak ditemukan. Install Docker Desktop terlebih dahulu."
}

# docker/.env
$DockerEnvExample = Join-Path $Root "docker\.env.example"
$DockerEnv = Join-Path $Root "docker\.env"
if (-not (Test-Path $DockerEnv)) {
    Copy-Item $DockerEnvExample $DockerEnv
}
(Get-Content $DockerEnv) `
    -replace '(?m)^APP_HOST=.*', "APP_HOST=$AppHost" `
    -replace '(?m)^APP_PORT=.*', "APP_PORT=$AppPort" | Set-Content $DockerEnv

# backend/.env
$BackendEnvExample = Join-Path $Root "backend\.env.example"
$BackendEnv = Join-Path $Root "backend\.env"
if (-not (Test-Path $BackendEnv)) {
    Copy-Item $BackendEnvExample $BackendEnv
}

$reverbKey = [Convert]::ToBase64String((1..24 | ForEach-Object { Get-Random -Maximum 256 }) -as [byte[]]).Substring(0, 20)
$reverbSecret = [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 }) -as [byte[]])

$backendContent = Get-Content $BackendEnv -Raw
$backendContent = $backendContent -replace '(?m)^APP_ENV=.*', 'APP_ENV=production'
$backendContent = $backendContent -replace '(?m)^APP_DEBUG=.*', 'APP_DEBUG=false'
$backendContent = $backendContent -replace '(?m)^APP_URL=.*', "APP_URL=$AppUrl"
$backendContent = $backendContent -replace '(?m)^DB_HOST=.*', 'DB_HOST=mysql'
$backendContent = $backendContent -replace '(?m)^REDIS_HOST=.*', 'REDIS_HOST=redis'

$dockerEnvLines = Get-Content $DockerEnv
$dbName = ($dockerEnvLines | Where-Object { $_ -match '^DB_DATABASE=' }) -replace '^DB_DATABASE=', ''
$dbUser = ($dockerEnvLines | Where-Object { $_ -match '^DB_USERNAME=' }) -replace '^DB_USERNAME=', ''
$dbPass = ($dockerEnvLines | Where-Object { $_ -match '^DB_PASSWORD=' }) -replace '^DB_PASSWORD=', ''
if ($dbName) { $backendContent = $backendContent -replace '(?m)^DB_DATABASE=.*', "DB_DATABASE=$dbName" }
if ($dbUser) { $backendContent = $backendContent -replace '(?m)^DB_USERNAME=.*', "DB_USERNAME=$dbUser" }
if ($dbPass) { $backendContent = $backendContent -replace '(?m)^DB_PASSWORD=.*', "DB_PASSWORD=$dbPass" }
$backendContent = $backendContent -replace '(?m)^FRONTEND_URL=.*', "FRONTEND_URL=$AppUrl"
$backendContent = $backendContent -replace '(?m)^SANCTUM_STATEFUL_DOMAINS=.*', "SANCTUM_STATEFUL_DOMAINS=$AppHost,localhost,127.0.0.1"
$backendContent = $backendContent -replace '(?m)^REVERB_HOST=.*', "REVERB_HOST=$AppHost"
$backendContent = $backendContent -replace '(?m)^REVERB_PORT=.*', "REVERB_PORT=$AppPort"
$backendContent = $backendContent -replace '(?m)^REVERB_SCHEME=.*', "REVERB_SCHEME=$AppScheme"
$backendContent = $backendContent -replace '(?m)^REVERB_APP_KEY=.*', "REVERB_APP_KEY=$reverbKey"
$backendContent = $backendContent -replace '(?m)^REVERB_APP_SECRET=.*', "REVERB_APP_SECRET=$reverbSecret"
Set-Content $BackendEnv $backendContent.TrimEnd()

# frontend/.env.local (relative API — same origin via nginx)
$FrontendEnv = Join-Path $Root "frontend\.env.local"
@(
    "# Auto-generated by install-client.ps1",
    "NEXT_PUBLIC_API_URL=/api/v1"
) | Set-Content $FrontendEnv

Push-Location (Join-Path $Root "docker")

Write-Host "Membangun dan menjalankan container..." -ForegroundColor Yellow
docker compose -f docker-compose.client.yml up -d --build

Write-Host "Menunggu MySQL siap..."
for ($i = 1; $i -le 45; $i++) {
    docker compose -f docker-compose.client.yml exec -T mysql mysqladmin ping -h localhost 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "MySQL siap."
        break
    }
    Start-Sleep -Seconds 2
}

docker compose -f docker-compose.client.yml exec -T backend php artisan key:generate --force
docker compose -f docker-compose.client.yml exec -T backend php artisan storage:link --force 2>$null

if ($SkipSeed) {
    docker compose -f docker-compose.client.yml exec -T backend php artisan migrate --force
} else {
    docker compose -f docker-compose.client.yml exec -T backend php artisan migrate --seed --force
}

docker compose -f docker-compose.client.yml exec -T backend php artisan config:cache
docker compose -f docker-compose.client.yml exec -T backend php artisan route:cache

Pop-Location

Write-Host "`n=== Instalasi selesai ===" -ForegroundColor Green
Write-Host "Web    : $AppUrl"
Write-Host "POS    : $AppUrl/pos"
Write-Host "Daftar : $AppUrl/register"
Write-Host "`nAndroid: pasang APK lalu arahkan ke $AppUrl"
Write-Host "Lihat docs/CLIENT-INSTALL.md untuk detail.`n"